package com.octagami.idols.commands;


import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;

import com.octagami.idols.event.CustomEvent;

public class Commandevent extends IdolsCommand {

	public Commandevent() {
		super("event");
	}

	@Override
	public void runCommand(final CommandSender sender, final Command command, final String commandLabel, final String[] args) throws Exception {

		// Create the event
		CustomEvent event = new CustomEvent("This message was generated by a custom event!");
		// Call the event
		Bukkit.getServer().getPluginManager().callEvent(event);

	}

}
